CREATE TYPE LUNCH_TYPE AS ENUM('Free or Reduced', 'Standard');
CREATE TYPE SUBJECTS AS ENUM('MATH','READING', 'WRITING');
CREATE TYPE ROLE_CATEGORY as ENUM('STUDENT', 'PROFESSOR', 'PROFESSOR''s ASSISTANT', 'ADMINISTRATION');
CREATE TYPE PARENT_EDUCATION as ENUM('High School', 'Bachelor''s', 'Master''s', 'PhD');
CREATE TYPE DEPARTMENT as ENUM('MATH', 'ENGLISH', 'SCIENCE');


CREATE TABLE Users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    username VARCHAR(30) UNIQUE, 
    password_hash VARCHAR(162),
    email VARCHAR(100) UNIQUE,
    user_name VARCHAR(40),
    user_role ROLE_CATEGORY,
    gender VARCHAR(10),
    birthday DATE,
    profile_picture TEXT
);

CREATE TABLE Students(
    user_id INTEGER PRIMARY KEY REFERENCES Users(user_id),
    grade_level INTEGER,
    parent_education PARENT_EDUCATION,
    lunch_type LUNCH_TYPE,
    internet_access BOOLEAN,
    extra_activities BOOLEAN
);

CREATE TABLE Professors(
    professor_id INTEGER PRIMARY KEY REFERENCES Users(user_id),
    department DEPARTMENT
);

-- student_name, gender, birthday, grade_level, parent_education, lunch_type, internet_access,extra_activities

INSERT INTO Students(user_id, grade_level, parent_education, lunch_type, internet_access, extra_activities) 
VALUES (1, 12, 'Bachelor''s', 'Standard', TRUE, TRUE);

CREATE TABLE StudentAttendance (
    attendance_id INTEGER PRIMARY KEY,
    user_id INTEGER REFERENCES Students(user_id),
    attendance_date DATE,
    is_present BOOLEAN
);


-- student_id,name,gender,birthday,grade_level,math_score,reading_score,writing_score,attendance_rate,
-- parent_education,study_hours,internet_access,lunch_type,extra_activities,final_result

CREATE TYPE GRADE_CATEGORY as ENUM('Assignment', 'Quiz', 'Exam', 'Project', 'Attendance');

CREATE TABLE Grades (
    grade_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES Users(user_id),
    grade_subject SUBJECTS,
    grade_task VARCHAR(200),
    grade_type GRADE_CATEGORY,
    date_assigned DATE,
    deadline DATE
);

CREATE TABLE GradesSubmition (
    grade_id INTEGER REFERENCES Grades(grade_id),
    user_id INTEGER REFERENCES Students(user_id),
    grade NUMERIC,
    date_submitted DATE,
    PRIMARY KEY (grade_id, user_id)
);



CREATE TABLE Class (
    class_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    class_name VARCHAR(40),
    class_codification_number INTEGER,
    class_subject CHAR(4)
);

INSERT INTO Class (class_name, class_codification_number, class_subject) VALUES
('Introduction to Mathematics', 1001, 'MATH'),
('Introduction to English', 1001, 'ENGL');



CREATE TABLE ClassUser(
    class_id INTEGER REFERENCES Class(class_id),
    user_id INTEGER REFERENCES Users(user_id),
    PRIMARY KEY (class_id, user_id)
);

INSERT INTO ClassUser(class_id, user_id) VALUES 
(1,1),
(1,2);


CREATE TABLE ApproveUsers(
    approve_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(30) UNIQUE, 
    password_hash VARCHAR(162),
    email VARCHAR(100) UNIQUE,
    user_name VARCHAR(40),
    user_role ROLE_CATEGORY,
    gender VARCHAR(10),
    birthday DATE,
    profile_picture TEXT,
    grade_level INTEGER,
    parent_education PARENT_EDUCATION,
    lunch_type LUNCH_TYPE,
    internet_access BOOLEAN,
    extra_activities BOOLEAN,
    department DEPARTMENT
);

INSERT INTO ApproveUsers(username, password_hash, email, user_name, user_role, gender, birthday, 
grade_level, parent_education, lunch_type, internet_access, extra_activities, department) VALUES
('TESTAprr1', 'fdsfsdfs', 'email1@email.com', 'TEST USER1', 'STUDENT', 'M', '2001-08-16', 
12,'PhD', 'Standard', True, True, null),
('TESTAprr2', 'fdsfsdfs', 'email2@email.com', 'TEST USER2', 'STUDENT', 'M', '2001-08-16', 
12,'PhD', 'Standard', True, True, null);