CREATE TYPE LUNCH_TYPE AS ENUM('Free or reduced', 'Standard');
CREATE TYPE SUBJECTS AS ENUM('MATH','READING', 'WRITING');

CREATE TABLE Students(
    student_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_name VARCHAR(25),
    gender VARCHAR(10),
    age INTEGER,
    grade_level INTEGER,
    parent_education VARCHAR(30),
    lunch_type LUNCH_TYPE,
    internet_access BOOLEAN,
    extra_activities BOOLEAN
);



CREATE TABLE StudentAttendance (
    attendance_id INTEGER PRIMARY KEY,
    student_id INTEGER REFERENCES Students(student_id),
    attendance_date DATE,
    is_present BOOLEAN
);


-- student_id,name,gender,age,grade_level,math_score,reading_score,writing_score,attendance_rate,
-- parent_education,study_hours,internet_access,lunch_type,extra_activities,final_result

CREATE TYPE GRADE_CATEGORY as ENUM('Assignment', 'Quiz', 'Exam', 'Project', 'Attendance');

CREATE TABLE Grades (
    grade_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id INTEGER REFERENCES Students(student_id),
    grade_subject SUBJECTS,
    grade_name VARCHAR(200),
    grade_type GRADE_CATEGORY,
    grade NUMERIC,
    date_assigned DATE,
    deadline DATE,
    date_submitted DATE
);

INSERT INTO Students(student_name, gender, age, grade_level, parent_education, lunch_type, internet_access, extra_activities) 
VALUES ('Luis E. Fernandez', 'M', 23, 12, 'Bachellor''s', 'Standard', TRUE, TRUE);